### ISSUE TITLE
yajl-ruby installation errors

### ISSUE THREAD

**Issue by ragaraga** [nandomoreirame/simplest#10]
hello, can you help me debug this install error? i'm a little new to ruby and jekyll. i'm using debian 9, ruby v2.3.3, gem v2.5.2.1, jekyll v3.1.6.
	
	user@server:/var/www/simplest$ bundle install
	Fetching gem metadata from http://rubygems.org/.........
	Fetching version metadata from http://rubygems.org/..
	Fetching dependency metadata from http://rubygems.org/.
	Using i18n 0.7.0
	Using json 1.8.3
	Using minitest 5.8.3
	Using thread_safe 0.3.5
	Using addressable 2.4.0
	Using sass 3.4.20
	Using thor 0.19.1
	Using bundler 1.15.4
	Using colorator 0.1
	Using colored 1.2
	Using ffi 1.9.10
	Using mercenary 0.3.5
	Using mini_portile2 2.0.0
	Using parallel 1.6.1
	Using yell 2.0.5
	Using rb-fsevent 0.9.7
	Using kramdown 1.9.0
	Using liquid 3.0.6
	Using rouge 1.10.1
	Using safe_yaml 1.0.4
	Using jekyll-paginate 1.1.0
	Using posix-spawn 0.3.11
	Fetching yajl-ruby 1.2.1
	Installing yajl-ruby 1.2.1 with native extensions
	Using tzinfo 1.2.2
	Using jekyll-sass-converter 1.4.0
	Fetching bourbon 4.2.6
	Installing bourbon 4.2.6
	Using ethon 0.8.0
	Using rb-inotify 0.9.5
	Fetching nokogiri 1.6.7.1
	Installing nokogiri 1.6.7.1 with native extensions
	Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1/.gitignore
	An error occurred while installing yajl-ruby (1.2.1), and Bundler cannot continue.
	Make sure that `gem install yajl-ruby -v '1.2.1'` succeeds before bundling.

	In Gemfile:
	  pygments.rb was resolved to 0.6.3, which depends on
	    yajl-ruby
	user@server:/var/www/simplest$ gem install yajl-ruby -v '1.2.1'
	ERROR:  While executing gem ... (Errno::EACCES)
	    Permission denied @ rb_sysopen - /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1/.gitignore
	user@server:/var/www/simplest$ exit
	exit
	root@server:/var/www/simplest# gem install yajl-ruby -v '1.2.1'
	Building native extensions.  This could take a while...
	ERROR:  Error installing yajl-ruby:
		ERROR: Failed to build gem native extension.

	    current directory: /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1/ext/yajl
	/usr/bin/ruby2.3 -r ./siteconf20171020-18457-wibsbf.rb extconf.rb
	creating Makefile

	current directory: /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1/ext/yajl
	make "DESTDIR=" clean
	sh: 1: make: not found

	current directory: /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1/ext/yajl
	make "DESTDIR="
	sh: 1: make: not found

	make failed, exit code 127

	Gem files will remain installed in /var/lib/gems/2.3.0/gems/yajl-ruby-1.2.1 for inspection.
	Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/yajl-ruby-1.2.1/gem_make.out
	root@server:/var/www/simplest#

**Comment by ragaraga** [comment]
> $ apt-get install build-essential

**Comment by nandomoreirame** [comment]
👍
